#Site settings
description: > # this means to ignore newlines until "baseurl:"
  Git Camp helps you get better at git
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://git.camp" # the base hostname & protocol for your site
permalink: /:title/

# Build settings
markdown: kramdown
